### ISSUE TITLE
validation frozen

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Old_Russian-RNC#2]
@dan-zeman, the data was updated and pushed to dev on Mar 29, 2022, but the page http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl reports errors are still there, the validation script last run Sat Mar 19 08:53:58 CET 2022

**Comment by dan-zeman** [comment]
Hi Olga, thanks for reporting. I don't know what kind of glitch it was but now it works (with a small change in the data back and forth, I re-drew the validator's attention to the treebank) and it is valid.
